### ISSUE TITLE
Audio Extract

### ISSUE THREAD

**Issue by di48l069** [di48l069/Flash-dl#11]
`public bool CanExtractAudio { get { return this.VideoType == VideoType.Flash; } }`

So only flash is extractable... 
Guess this might be a problem if or when youtube decides to completely drop their flashsupport.

Does it support to extraction sound from .mp4?

**Comment by Kimmax** [comment]
Where did you find this?
My code looks like this:
```C#
public bool CanExtractAudio
{
    get { return this.VideoType != VideoType.Unknown; }
}
```
We can download any format, except Video dash, because they don't have audio lol.
Even audio dash works which gives us the ability to download audio only which speeds things up dramatically.
Best audio I downloaded with my app is 256kbits AAC, although the video didn't offered more :sunglasses:

**Comment by di48l069** [comment]
Haha sorry was looking at wrong respro haha
