### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by di48l069** [di48l069/Flash-dl#12]
Ideas of having console setting such as

<h3>General Settings</h3>
- Setting API key
- Save path

<h3>Video Settings</h3>
- Setting Video quality to download
....

<h3>AudioSettings</h3>
- Setting Audio quality to download

Just basic concept ofcause there are various other settings. <b>All settings must be able to set in console</b>

**Comment by Kimmax** [comment]
Shouldnt be a problem, zou could use the Properties class for that.
But never ever make an api key public.
For now we can go with the api key per user approch, but later we should do some proxying, I already started work on this

**Comment by di48l069** [comment]
@Kimmax Sounds good

**Comment by di48l069** [comment]
@Kimmax how does this proxy work is flash-dl gana have its on proxy? and what are the benifits sorry very new at this

**Comment by Kimmax** [comment]
If you go public you need a more powerful api key for the google youtube api, because there will be many more requests. We get this key from google but since it's way more powerful we need to keep it secret and there is no way to keep it secret when shipping it with the application itself straight to the user, who could possibly decompile and read the key. 
To go arround this issue we build a little server. All request from the app go to this server instead of google directly and handels the connection to google with the (now private) key. 
One benefit also is that we could block users who use the app excessive (eg trying to download whole youtube, which would kill our key usage limit's quickly)

**Comment by di48l069** [comment]
Thats really cool does google not have piracy issues downloading there videos and audio haha?

**Comment by Kimmax** [comment]
They won't  be able to track it. Well they could but nah.
We are using the official api to gather infos about the video, title, channel etc. And than you can generate a direct link to the video / audio file on googles server itself, which than would be downloaded by the user. 
For google it'll most likely look like a normal video playback in a browser, except there would be many of them from one ip.
Of course they could bloch the user, but it looks like they dont care. At least downloading ~320 videos didn't get be blocked.

**Comment by di48l069** [comment]
@Kimmax cool cool

**Comment by di48l069** [comment]
@Kimmax if user was able to set setting like what would he be allowed to send

**Comment by Kimmax** [comment]
Everything that doesn't affect the api settings like
-Quality
-Audio only
-Output format
-Check for duplicate before downloading
-Name format regex
-ID3 Tag settings
Something else I forgot?

**Comment by di48l069** [comment]
:+1: Sounds good so far

**Comment by Kimmax** [comment]
Settings can now be changed via the `SYMM Settings object`.
Following properties can be changed
- [x] Quality
- [x]  Audio only
- [x]  Output format
- [ ]  Check for duplicate before downloading _(Code need to be moved into backend)_
- [ ]  Name format regex _(No code base yet)_
- [ ]  ID3 Tag settings _(No code base yet)_
The settings object is not implemented into the frontend yet, but the backend is ready to go.
