### ISSUE TITLE
Streaming?

### ISSUE THREAD

**Issue by p1Ggy** [di48l069/Flash-dl#17]
Hello @Kimmax,

How would I stream without using the API key is that possible or is the API Key required?

**Comment by Kimmax** [comment]
It's been a while. But I'm pretty confident, that the stream function does not use the youtube api, so just try providing any string as key.
If you get any 401's you need a key. I'm not even sure if the backend still works, the extract functions haven't been updated in a while

**Comment by p1Ggy** [comment]
@Kimmax ya I receive this

```
Flash-dl> StreamAudio https://www.youtube.com/watch?v=5LxBx2Z0I6s
Loading data..
Google.Apis.Requests.RequestError
Bad Request [400]
Errors [
        Message[Bad Request] Location[ - ] Reason[keyInvalid] Domain[usageLimits]
]
```

**Comment by Kimmax** [comment]
Yeah, so as you can see it response with `keyInvalid`, so it indeed uses the YouTube API. In that case you _need_ a working key. You could implement and run a proxy server somewhere, so that you don't have to handle the API stuff client side or you will have to throw out the SYMM Backend and find another solution

**Comment by p1Ggy** [comment]
Ya thanks @Kimmax
